#All options are straightforward. Put the names of your worlds (CASE-SENSITIVE) in which you want 1.8 terrain to generate in.
options:
    sheep:
        dropMutton: true
    creeper:
        dropMobHead: true
    worlds: [world]
    
donottouch.configVersion: 0.3